name: 🔄 Refactor
description: Code improvement or structural changes
title: "[REFACTOR] "
labels: ["refactor"]
body:
  - type: textarea
    attributes:
      label: 📌 Refactor Description
      description: What part of the code needs improvement?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎯 Purpose
      description: Why is this refactor necessary?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📋 Checklist
      placeholder: |
        - [ ] No breaking changes
        - [ ] Tests updated
        - [ ] Performance validated